### ISSUE TITLE
generator animation

### ISSUE THREAD

**Issue by chassain** [mykle1/MMM-Aurora#1]
Hello mykle,

Happy to see you here again :)...i was working to catch source code video from noaa's website and i wanted to writte you...But your module exist :)

Working for radio department i m interresting to see the animation of this  module, like the video website..Do you think it could be possible ?
And last question...If i change the adress to see the other animation (solar,....), i have to change only on your aurora.js

Thanks

**Comment by chassain** [comment]
it's working when i change adress to see /animation/enlil :)

**Comment by mykle1** [comment]
I'm not sure I understand what you want but I'll try to help you on the forum. There is no issue with the module itself. So, please post of the forum and I'll see you there.
